apiVersion: argoproj.io/v1aplha1
kind: Application

metadata:
  name: nginx-prod
  namespace: argocd

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
    project: default

  source:
    helm:
      valueFiles: 
      - values-prod.yaml
      path: helm
      repoURL : https://github.com/matrxi/nd064_course_1
      targetRevision: HEAD
