apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: techtrends
  ports:
  - port: {{ .Values.service.ports }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPorts }}
  type: {{ .Values.service.type }}
