namespace:
  name: sandbox

service:
  port: 3111
  protocol: TCP
  targetPort: 4111
  type : ClusterIP


image:
  repository: matrxi/techtrends
  tag: latest
  imagePullPolicy : IfNotPresent

replicaCount: 1


resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort : 3111


readinessProbe:
  httpGet:
    path: /healthz

livenessProbe:
  httpGet:
    path: /healthz
